spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: accabba
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
app:
  cors:
    allowed-origins: http://localhost:3000